name: "Ferme les vieux bugs"
on:
  schedule:
  - cron: "0 9 * * 1"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v6
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "Ce bug est fermé à cause d'une trop longue inactivité"