name: "Close old bugs"
on:
  schedule:
  - cron: "0 9 * * 1"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This bug is closed du to a too long inactivity"