name: variables - exercice 1

on:
  workflow_dispatch:
  
jobs:
  job1: 
    runs-on: ubuntu-latest
    env:
      VAR1: "hello"
    
    steps:
    - run: |
        VARTMP=$VAR1
        echo "VAR2=$VARTMP" >> $GITHUB_ENV 
    - run: echo $VAR2
