name: "matrix - exercise 1"

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        dotnet: [4.2.x, 5.0.x]
        buildMode: [Debug, Release]
    runs-on: windows-latest
    steps:
      - name: Recupere le code source
        uses: actions/checkout@v4
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.buildMode }}
        env:
          buildMode: ${{ matrix.buildMode }}