name: "triggers - exercise 1"
on:
  schedule:
  - cron: "30 19 * * 1-5"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This bug is open for 30 days with any activity. It will be closed in 5 days'
        days-before-stale: 30
        days-before-close: 5